# Generated by Django 4.2.24 on 2025-12-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="model",
            field=models.CharField(default="gpt-4o-mini", max_length=100),
        ),
    ]
