# Generated by Django 4.2.24 on 2025-12-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_settings_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="model",
            field=models.CharField(default="gemini-1.5-pro", max_length=100),
        ),
    ]
